version: '3.8'
services:
  web:
    container_name: cloudaat
    image: webapp
    restart : always
    build: .
    ports:
    - "8050:8050"

    links:
    - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
    - '27017:27017'
